config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events, :only => [:index, :new, :create, :show]
  post '/events'    => 'events#create'
  resources :tickets
  get 'home/hello'
  root :to => 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
require 'date'


class EventValidator < ActiveModel::Validator
  def validate(record)

    if record.event_date < Date.today
      record.errors[:base] << "Data wydarzenia nie może być z przeszłości"
    end

    if record.price_high < record.price_low
      record.errors[:base] << "Dolna granica cenowa nie może być większa od górnej"
    end
  end
end

class Event < ApplicationRecord
  has_many :tickets

  NUM_VALUES = /\A\d+(?:\.\d{2})?\z/

  validates :artist, :presence => true
  validates :price_low, :presence => true,
            format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
  validates :price_high, :presence => true,
            format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
  validates :event_date, :presence => true

  validates_with EventValidator, fields: [:event_date, :price_low, :price_high], :if => :event_date, :presence => true,
                 :if => :price_low, :presence => true, :if => :price_high, :presence => true



end

app/models/ticket.rb
class TicketValidator < ActiveModel::Validator
  def validate(record)
    event = Event.find(record.event_id)
    if (event.price_low > record.price) or (event.price_high < record.price)
      record.errors[:base] << "Cena biletu musi mieścić się w przedziale cenowym dla wydarzenia"
    end
  end
end

class Ticket < ApplicationRecord
  belongs_to :event
  belongs_to :user

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
            :length => { :minimum => 6 }
  validates :email, :presence => true,
            format: { with: VALID_EMAIL_REGEX }
  validates :price, :presence => true,
            format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
  validates :address, :presence => true
  validates :seat_id_seq, :presence => true,
            :length => { :minimum => 2 }
  validates :phone, :presence => true,
            :length => { :minimum => 9 }

  validates_with TicketValidator, fields: [:event_id, :price], :if => :event_id, :presence => true,
                 :if => :price
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  #   # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    def hello
      render plain: "hello, world!"
    end

    def goodbye
      render plain: "goodbye!"
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_logged_in, :only => [:new, :create]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    event_parmas =  params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date)

    @event = Event.new(event_parmas)

    if @event.save
      flash[:komunikat] = 'Event został poprawnie stworzony.'
      redirect_to "/events/#{@event.id}"
      else
        render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def check_logged_in
    authenticate_or_request_with_http_basic("Ads") do |username, password|
      username == "admin" && password == "admin"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def hello
    random_names = ["Ala", "Ola", "Ula"]
    @name = random_names.sample
    @time = Time.now
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = current_user.tickets.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = current_user.tickets.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticket= current_user.tickets.find_by(id: params[:id])
    redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email, :phone, :event_id)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def formatted_time(time)
    time.strftime("%I:%M%p")    # time string in AM/PM format end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_new_ticket.html.erb
<h3 class="display-2">Kup bilet</h3>
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= form.label :id %>
    <%= form.hidden_field :event_id, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="actions row">
    <%= form.submit "zakup bilet", class: "btn btn-lg btn-primary  event-buttons" %>
    <%= link_to 'powrót do listy', events_path, class: "btn btn-lg btn-primary button  event-buttons" %>
  </div>
<% end %>

app/views/events/_tickets_list.html.erb
<br><br>
<h3 class="display-2">Wykupione bilety</h3>

<table class="table">
  <thead>
  <tr>
    <th>Dane</th>
    <th>ID miejsca</th>
    <th>Adres</th>
    <th>Cena</th>
    <th>Email</th>
    <th>Telefon</th>
  </tr>
  </thead>

  <tbody>
  <% tickets.each do |tickett| %>
    <tr>
      <td><%= tickett.name %></td>
      <td><%= tickett.seat_id_seq %></td>
      <td><%= tickett.address %></td>
      <td><%= tickett.price %></td>
      <td><%= tickett.email %></td>
      <td><%= tickett.phone %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/events/index.html.erb
<div class="jumbotron">
<div class="container">
  <div class="row event-list">
    <h1 class="display-1"> Wszystkie wydarzenia</h1>
    <br><br>
    <ul class="list-group event-list list-container">
      <li class="list-group-item list-group-item-info event-list-title" id="event-list-title-id">
        <div class="col-12">
          <div class="row">
            <span class="col-xs-7 col-sm-9 ">Artysta</span>
            <span class="col-xs-5 col-sm-3 text-right title_date">Termin</span>
          </div>
        </div>
      </li>
      <% for event in @events %>
        <li class="list-group-item list-group-item-info">
          <div class="col-12">
            <%= link_to event, class: "row" do %>
              <%= content_tag :div, event.artist, class: "col-xs-7 col-sm-9" %>
              <%= content_tag :div, event.event_date, class: "col-xs-5 col-sm-3 text-right" %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
    <%= link_to 'nowe wydarzenie', new_event_path, class: "btn btn-lg btn-primary button" %>
  </div>
</div>
</div>

app/views/events/new.html.erb
<div class="jumbotron vertical-center">
<div class="container">
  <div class="row">
    <div class="col-xs-0 col-sm-2 col-md-3"></div>
    <div class="col-xs-12 col-sm-8 col-md-6 main-part">
      <h1 class="display-1"> Dodaj wydarzenie</h1>
      <%= form_with(model: @event, local: true) do |form| %>
        <% if @event.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :"Artysta" %>
          <%= form.text_field :artist, class: "form-control" %>
        </div>

        <div class="field">
          <%= form.label :"Krótki opis" %>
          <%= form.text_field :description, class: "form-control"  %>
        </div>

        <div class="field">
          <%= form.label :"Cena minimalna" %>
          <%= form.text_field :price_low, class: "form-control"  %>
        </div>

        <div class="field">
          <%= form.label :"Cena maksymalna" %>
          <%= form.text_field :price_high, class: "form-control"  %>
        </div>

        <div class="field">
          <%= form.label :"Data wydarzenia" %>
          <%= form.date_select :event_date, class: "form-control input-lg"  %>
        </div>

        <div class="actions">
          <%= form.submit class: "btn btn-lg btn-primary" %>
        </div>
      <% end %>
    </div>

  </div>
</div>
</div>

app/views/events/show.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <h1 class="display-1"> Wydarzenie </h1>

      <br>
      <p id="komunikat"><%= flash[:komunikat] %></p>

      <h3 class="display-2">Szczegóły</h3>

      <div class="col-xs-12 content">
        <div class="row">
<!--          <div class="col-xs-0 col-sm-2 col-md-3"></div>-->
          <div class="col-xs-12 col-sm-8 col-md-6">
            <div class="row info-row">
              <div class="col-xs-6"><strong>Artysta:</strong></div>
              <div class="col-xs-6 text-right"><%= @event.artist %></div>
            </div>
          </div>
        </div>
        <div class="row">
<!--          <div class="col-xs-0 col-sm-2 col-md-3"></div>-->
          <div class="col-xs-12 col-sm-8 col-md-6">
            <div class="row info-row">
              <div class="col-xs-6"><strong>Opis:</strong></div>
              <div class="col-xs-6 text-right"><%= @event.description %></div>
            </div>
          </div>
        </div>
        <div class="row">
<!--          <div class="col-xs-0 col-sm-2 col-md-3"></div>-->
          <div class="col-xs-12 col-sm-8 col-md-6">
            <div class="row info-row">
              <div class="col-xs-6"><strong>Minimalna cena:</strong></div>
              <div class="col-xs-6 text-right"><%= @event.price_low %></div>
            </div>
          </div>
        </div>
        <div class="row">
<!--          <div class="col-xs-0 col-sm-2 col-md-3"></div>-->
          <div class="col-xs-12 col-sm-8 col-md-6">
            <div class="row info-row">
              <div class="col-xs-6"><strong>Maksymalna cena:</strong></div>
              <div class="col-xs-6 text-right"><%= @event.price_high %></div>
            </div>
          </div>
        </div>
        <div class="row">
<!--          <div class="col-xs-0 col-sm-2 col-md-3"></div>-->
          <div class="col-xs-12 col-sm-8 col-md-6">
            <div class="row info-row">
              <div class="col-xs-6"><strong>Data:</strong></div>
              <div class="col-xs-6 text-right"><%= @event.event_date %></div>
            </div>
          </div>
        </div>
      </div>

      <br>

      <br>
      <%= render "tickets_list",  tickets: @event.tickets %>
      <br>
      <div class="col-xs-12 col-sm-8 col-md-6">
        <% if user_signed_in? %>
          <%= render "new_ticket",  ticket: Ticket.new( :event_id => @event.id) %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/home/hello.html.erb
<h1>Hej, <%= @name %></h1>
<p>Jest teraz godzina <%= formatted_time(@time) %> </p>
<p><%= link_to "Google", "http://www.google.com" %></p>
<p><%= link_to "Goodbye", home_hello_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bilecik</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="navbar-textpull-right">
    <div class="row">
      <div class="col-xs-12 col-sm-6 nav-bar-right-text">
        <% if user_signed_in? %>
          Zalogowany jako: <strong><%= current_user.email %></strong>.
          <%= link_to 'Edycja profilu', edit_user_registration_path, :class => 'navbar-link link-devise-menu' %> |
          <%= link_to "Wyloguj", destroy_user_session_path, method: :delete, :class => 'navbar-link link-devise-menu' %>
        <% else %>
          <%= link_to "Rejestracja", new_user_registration_path, :class => 'navbar-link link-devise-menu' %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link link-devise-menu' %>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-6 text-right">
        <%= link_to "wydarzenia", events_path, :class => 'navbar-link link-devise-menu btn btn-primary main-page-menu-btn' %>
        <%= link_to "bilety", tickets_path, :class => 'navbar-link link-devise-menu btn btn-primary main-page-menu-btn ' %>
      </div>
    </div>
  </p>


    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tickets/_events_list.html.erb
<table class="table">
  <thead>
  <tr>
    <th>ID wydarzenia</th>
    <th>Artysta</th>
    <th>Opis</th>
    <th>Cena minimalna</th>
    <th>Cena maksymalna</th>
    <th>Data</th>
  </tr>
  </thead>

  <tbody>
  <% events.each do |eventt| %>
    <tr>
      <td><%= eventt.id %></td>
      <td><%= eventt.artist %></td>
      <td><%= eventt.description %></td>
      <td><%= eventt.price_low %></td>
      <td><%= eventt.price_high %></td>
      <td><%= eventt.event_date %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :"ID wydarzenia" %>
    <%= form.text_field :event_id, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :"Dane osobowe" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :"ID miejsca" %>
    <%= form.text_field :seat_id_seq, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :adres %>
    <%= form.text_area :address, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :cena %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :telefon %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="actions row">
    <%= form.submit "zakup bilet", class: "btn btn-lg btn-primary event-buttons" %>
    <%= link_to 'powrót do listy', tickets_path, class: "btn btn-lg btn-primary event-buttons" %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <h1>Edycja biletu</h1>
      <br>
      <h3 class="display-2">Dostępne wydarzenia</h3>
      <%= render "events_list",  events: Event.all %>
      <br>
      <h3 class="display-2">Wypełnij formularz</h3>
      <%= render 'form', ticket: @ticket %>

    </div>
  </div>
</div>

app/views/tickets/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <h1>Lista biletów</h1>

      <p id="notice"><%= notice %></p>



      <table class="table">
        <thead>
          <tr>
            <th>Dane osobowe</th>
            <th>ID miejsca</th>
            <th>Adres</th>
            <th>Cena</th>
            <th>Email</th>
            <th>Telefon</th>
            <th colspan="3"></th>
          </tr>
        </thead>



        <tbody>
          <% @tickets.each do |ticket| %>
            <tr>
              <td><%= ticket.name %></td>
              <td><%= ticket.seat_id_seq %></td>
              <td><%= ticket.address %></td>
              <td><%= ticket.price %></td>
              <td><%= ticket.email %></td>
              <td><%= ticket.phone %></td>

              <td><%= link_to 'szczegóły', ticket, class: "btn btn-xs btn-primary" %></td>

              <% if ticket.user == current_user and user_signed_in? %>
                <td>
                  <%= link_to 'edytuj', edit_ticket_path(ticket), class: "btn btn-xs btn-primary"  %>
                </td>
                <td>
                  <%= link_to 'usuń', ticket, method: :delete, data: { confirm: 'Jesteś pewien?' }, class: "btn btn-xs btn-primary"  %>
                </td>
              <% end %>


<!--              <td></td>-->
<!--              <td></td>-->
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'dodaj bilet', new_ticket_path, class: "btn btn-xl btn-primary" %>
    </div>
  </div>
</div>

app/views/tickets/new.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <h1>Kup bilet</h1>
      <br>
      <h3 class="display-2">Lista dostępnych wydarzeń</h3>
      <%= render "events_list",  events: Event.all %>
      <br>
      <h3 class="display-2">Uzupełnij formularz</h3>
      <%= render 'form', ticket: @ticket %>
    </div>
  </div>
</div>

app/views/tickets/show.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <h1>Szczegóły biletu</h1>





<!--      <h3 class="display-2">Szczegóły</h3>-->

      <p id="notice"><%= notice %></p>
      <br>

      <div class="col-xs-12 content">
        <div class="row">
          <!--          <div class="col-xs-0 col-sm-2 col-md-3"></div>-->
          <div class="col-xs-12 col-sm-8 col-md-6">
            <div class="row info-row">
              <div class="col-xs-6"><strong>Dane osobowe:</strong></div>
              <div class="col-xs-6 text-right"><%= @ticket.name %></div>
            </div>
          </div>
        </div>
        <div class="row">
          <!--          <div class="col-xs-0 col-sm-2 col-md-3"></div>-->
          <div class="col-xs-12 col-sm-8 col-md-6">
            <div class="row info-row">
              <div class="col-xs-6"><strong>ID miejsca:</strong></div>
              <div class="col-xs-6 text-right"><%= @ticket.seat_id_seq %></div>
            </div>
          </div>
        </div>
        <div class="row">
          <!--          <div class="col-xs-0 col-sm-2 col-md-3"></div>-->
          <div class="col-xs-12 col-sm-8 col-md-6">
            <div class="row info-row">
              <div class="col-xs-6"><strong>Adres:</strong></div>
              <div class="col-xs-6 text-right"><%= @ticket.address %></div>
            </div>
          </div>
        </div>
        <div class="row">
          <!--          <div class="col-xs-0 col-sm-2 col-md-3"></div>-->
          <div class="col-xs-12 col-sm-8 col-md-6">
            <div class="row info-row">
              <div class="col-xs-6"><strong>Cena:</strong></div>
              <div class="col-xs-6 text-right"><%= @ticket.price %></div>
            </div>
          </div>
        </div>
        <div class="row">
          <!--          <div class="col-xs-0 col-sm-2 col-md-3"></div>-->
          <div class="col-xs-12 col-sm-8 col-md-6">
            <div class="row info-row">
              <div class="col-xs-6"><strong>Email:</strong></div>
              <div class="col-xs-6 text-right"><%= @ticket.email %></div>
            </div>
          </div>
        </div>
        <div class="row">
          <!--          <div class="col-xs-0 col-sm-2 col-md-3"></div>-->
          <div class="col-xs-12 col-sm-8 col-md-6">
            <div class="row info-row">
              <div class="col-xs-6"><strong>Telefon:</strong></div>
              <div class="col-xs-6 text-right"><%= @ticket.phone %></div>
            </div>
          </div>
        </div>
      </div>

      <br>
      <%= link_to 'Back', tickets_path, class: "btn btn-lg btn-primary event-buttons" %>
      <% if @ticket.user== current_user and user_signed_in? %>
        <%= link_to 'Edit', edit_ticket_path(@ticket), class: "btn btn-lg btn-primary event-buttons" %>
      <% end %>
    </div>
  </div>
</div>